import CondUtils
import DCLayers
import DCsphere
import DCWidget
import MT
import sphereElectrostatic_example
import View
import VolumeWidget
import VolumeWidgetPlane
import DipoleWidgetFD
import DipoleWidgetTD
import PlanewaveWidget
import EMcircuit
import FreqtoTime
